source 'https://github.com/inacioferrarini/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

target 'VideoApp' do

    use_frameworks!

    pod 'PlaylistAppModule', :path => '../../Modules/PlaylistApp'

    target 'VideoAppTests' do
        inherit! :search_paths
    end

    target 'VideoAppUITests' do
        inherit! :search_paths
    end

end
